version: '3'

services:
  db:
    image: mariadb:10.8.2-rc-focal
    container_name: marinadb
    hostname: mariadb-mlops-study
    volumes:
      - ${PWD}/data/mlops_table_data:/tmp
      - ${PWD}/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
  adminer:
    image: adminer
    container_name: marinadb_adminer
    hostname: adminer-mlops-study
    restart: always
    ports:
      - "8089:8080"
networks:
  default:
    external:
      name: mlops_study_network
